name: ifinnance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  lottie: ^3.0.0
  path: ^1.8.3
  shimmer: ^3.0.0
  sqflite: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
